version: '3'

vars:
  OPENWRT_VERSIONS:
    sh: |
      echo "{" \
        "\"v24\": \"${OPENWRT_VERSION_24:-$(curl -s "https://api.github.com/repos/openwrt/openwrt/releases" | jq -r '[.[] | select(.tag_name | startswith("v24."))] | first | .tag_name | ltrimstr("v")')}\"", \
        "\"v25\": \"${OPENWRT_VERSION_25:-$(curl -s "https://api.github.com/repos/openwrt/openwrt/releases" | jq -r '[.[] | select(.tag_name | startswith("v25."))] | first | .tag_name | ltrimstr("v")')}\"" \
      "}"
  OPENWRT_VERSIONS_JSON:
    ref: "fromJson .OPENWRT_VERSIONS"
  OPENWRT_VERSION_24:
    ref: .OPENWRT_VERSIONS_JSON.v24
  OPENWRT_VERSION_25:
    ref: .OPENWRT_VERSIONS_JSON.v25
  BUILD_DIR: build
  OUTPUT_DIR: output

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
      - echo "Examples:"
      - echo "  OPENWRT_VERSION_24=24.10.1 task openwrt-24-virtualbox"
      - echo "  OPENWRT_VERSION_25=25.12.0 task openwrt-25-libvirt"
    silent: true

  fetch-image:
    internal: true
    vars:
      TIMESTAMP:
        sh: date +%s
      VM_NAME: openwrt-{{.OPENWRT_VERSION}}-{{.TIMESTAMP}}
    status:
      - test -f "{{.IMAGE_NAME}}.img" && test -f "{{.IMAGE_NAME}}.ovf"
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - echo "Fetching and extracting OpenWrt {{.OPENWRT_VERSION}} image..."
      - |
        wget -O "{{.IMAGE_NAME}}.img.gz" \
        "https://downloads.openwrt.org/releases/{{.OPENWRT_VERSION}}/targets/x86/64/openwrt-{{.OPENWRT_VERSION}}-x86-64-generic-ext4-combined.img.gz"
      - gzip -f -d "{{.IMAGE_NAME}}.img.gz" || true
      - echo "Converting image to VDI..."
      - VBoxManage convertfromraw --format VDI "{{.IMAGE_NAME}}.img" "{{.IMAGE_NAME}}.vdi"
      - echo "Creating VirtualBox VM..."
      - VBoxManage createvm --name "{{.VM_NAME}}" --ostype "Linux_64" --register
      - VBoxManage storagectl "{{.VM_NAME}}" --name SATA --add sata --controller IntelAHCI --portcount 1
      - VBoxManage storageattach "{{.VM_NAME}}" --storagectl SATA --port 0 --device 0 --type hdd --medium "{{.IMAGE_NAME}}.vdi"
      - VBoxManage export "{{.VM_NAME}}" --output "{{.IMAGE_NAME}}.ovf"
      - VBoxManage unregistervm "{{.VM_NAME}}" --delete

  build-box:
    internal: true
    deps:
      - task: fetch-image
        vars:
          OPENWRT_VERSION: "{{.OPENWRT_VERSION}}"
          IMAGE_NAME: "{{.IMAGE_NAME}}"
    vars:
      IMAGE_NAME: "{{.BUILD_DIR}}/openwrt-{{.OPENWRT_VERSION}}"
      BOX_FILE_NAME: '{{.OUTPUT_DIR}}/openwrt-{{.OPENWRT_BRANCH}}_{{.PROVIDER}}_{{.OPENWRT_VERSION}}.box'
      DESCRIPTION_FILE: '{{.OUTPUT_DIR}}/openwrt-{{.OPENWRT_BRANCH}}_{{.PROVIDER}}_{{.OPENWRT_VERSION}}.md'
      PACKER_ONLY: '{{if eq .PROVIDER "virtualbox"}}virtualbox-ovf.openwrt-virtualbox{{else}}qemu.openwrt-libvirt{{end}}'
    cmds:
      - echo "Building OpenWrt {{.OPENWRT_BRANCH}} ({{.OPENWRT_VERSION}}) [{{.PROVIDER}}]"
      - packer init build.pkr.hcl
      - |
        BUILD_DIR={{.BUILD_DIR}} \
        BOX_FILE_NAME={{.BOX_FILE_NAME}} \
        IMAGE_NAME={{.IMAGE_NAME}} \
        packer build \
          -only={{.PACKER_ONLY}} \
          -on-error=cleanup -force build.pkr.hcl

      - echo "Writing '{{.DESCRIPTION_FILE}}'"
      - |
        cat > {{.DESCRIPTION_FILE}} <<EOF
        **Updated OpenWrt to version {{.OPENWRT_VERSION}}**<br>
        https://github.com/cheretbe/vagrant-openwrt/blob/master/README.md
        EOF

  build-virtualbox:
    internal: true
    cmds:
      - task: build-box
        vars:
          OPENWRT_BRANCH: "{{.OPENWRT_BRANCH}}"
          PROVIDER: virtualbox
          OPENWRT_VERSION: "{{.OPENWRT_VERSION}}"

  build-libvirt:
    internal: true
    cmds:
      - sudo -n modprobe kvm_intel
      - defer: sudo -n rmmod kvm_intel kvm
      - task: build-box
        vars:
          OPENWRT_BRANCH: "{{.OPENWRT_BRANCH}}"
          PROVIDER: libvirt
          OPENWRT_VERSION: "{{.OPENWRT_VERSION}}"

  openwrt-24-virtualbox:
    desc: Build OpenWrt v24 VirtualBox box
    cmds:
      - task: build-virtualbox
        vars:
          OPENWRT_BRANCH: "24"
          OPENWRT_VERSION:
            ref: .OPENWRT_VERSION_24

  openwrt-24-libvirt:
    desc: Build OpenWrt v24 libvirt box
    cmds:
      - task: build-libvirt
        vars:
          OPENWRT_BRANCH: "24"
          OPENWRT_VERSION:
            ref: .OPENWRT_VERSION_24

  openwrt-24:
    desc: Build all OpenWrt v24 boxes
    cmds:
      - task: openwrt-24-virtualbox
      - task: openwrt-24-libvirt

  openwrt-25-virtualbox:
    desc: Build OpenWrt v25 VirtualBox box
    cmds:
      - task: build-virtualbox
        vars:
          OPENWRT_BRANCH: "25"
          OPENWRT_VERSION:
            ref: .OPENWRT_VERSION_25

  openwrt-25-libvirt:
    desc: Build OpenWrt v25 libvirt box
    cmds:
      - task: build-libvirt
        vars:
          OPENWRT_BRANCH: "25"
          OPENWRT_VERSION:
            ref: .OPENWRT_VERSION_25

  openwrt-25:
    desc: Build all OpenWrt v25 boxes
    cmds:
      - task: openwrt-25-virtualbox
      - task: openwrt-25-libvirt

  test:
    desc: Register temporary vagrant boxes and run basic tests
    cmds:
      - echo "[TODO] Test steps go here"

  cleanup:
    desc: Clean up build artifacts and temporary files
    cmds:
      - rm -vrf build
      - rm -vrf output

  build:
    desc: Build and test all OpenWrt boxes
    cmds:
      - task: cleanup
      - task: openwrt-24
      - task: openwrt-25
      - task: test